baseURL = "https://wonderful-pond-0f1879903.azurestaticapps.net/"
languageCode = "en-us"
title = "Cludo Documentation Hub"
theme = "book"

[params]
    BookLogo = "https://my.cludo.com/assets/img/logo/logo-top-nav-cut.svg"