baseURL = "https://purple-dune-037739410.azurestaticapps.net/"
languageCode = "en-us"
title = "Cludo Docs"
theme = "book"

[params]
    site_logo = "/img/cludo_docs_logo.svg"
    BookSearch = false
    BookToC = true
    SideMenu = true
    SubHeader = false
    gitLink = "https://github.com/Cludo/Cludo.DocumentationHub/blob/master/content/"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true