baseURL = "http://example.org/"
languageCode = "en-us"
title = "Cludo Docs"
theme = "book"

[params]
    site_logo = "https://my.cludo.com/assets/img/logo/logo-top-nav-cut.svg"
    ananke_process_css = true