baseURL = "https://purple-dune-037739410.azurestaticapps.net/"
languageCode = "en-us"
title = "Cludo Docs"
theme = "book"

[params]
    site_logo = "https://my.cludo.com/assets/img/logo/logo-top-nav-cut.svg"
    BookSearch = false
    BookToC = true
    SideMenu = true
    SubHeader = false
    
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true